In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
movies = pd.read_csv('C:/Users/Mitesh Soni/Desktop/Data/tmdb_5000_movies[1].csv')
credits = pd.read_csv('C:/Users/Mitesh Soni/Desktop/Data/tmdb_5000_credits[1].csv')

In [3]:
credits_1 = pd.read_csv('C:/Users/Mitesh Soni/Desktop/Data/credits[1].csv')
movies_1 = pd.read_csv('C:/Users/Mitesh Soni/Desktop/Data/movies_metadata.csv')

C:\Users\Mitesh Soni\AppData\Local\Temp\ipykernel_16892\1934180239.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_1 = pd.read_csv('C:/Users/Mitesh Soni/Desktop/Data/movies_metadata.csv')

In [4]:
credits_1.head(2)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844

In [122]:
movies_1.sample(20)

,movie_id,title,overview,genres,cast,crew,tags
40148,340485,American Honey,"[A, teenage, girl, with, nothing, to, lose, jo...",[Drama],"[SashaLane, ShiaLaBeouf, RileyKeough]",[AndreaArnold],"[A, teenage, girl, with, nothing, to, lose, jo..."
38244,35759,My Super Psycho Sweet 16,"[A, spoiled, teens, birthday, bash, turns, kil...",[Horror],"[JuliannaGuill, LaurenMcKnight, ChrisZylka]",[JacobGentry],"[A, spoiled, teens, birthday, bash, turns, kil..."
18843,43309,The Gamma People,"[An, American, reporter, smells, a, story, whe...","[ScienceFiction, Horror, Comedy]","[PaulDouglas, EvaBartok, LesliePhillips]",[JohnGilling],"[An, American, reporter, smells, a, story, whe..."
25193,58058,Elisa,"[Marie, has, had, a, tough, childhood, ever, s...",[Drama],"[VanessaParadis, ClotildeCourau, GérardDepardieu]",[JeanBecker],"[Marie, has, had, a, tough, childhood, ever, s..."
15178,62727,Pinky,"[Pinky,, a, light, skinned, black, woman,, ret...",[Drama],"[JeanneCrain, EthelBarrymore, EthelWaters]",[EliaKazan],"[Pinky,, a, light, skinned, black, woman,, ret..."
3360,25673,A Place in the Sun,"[An, ambitious, young, man, wins, an, heiress'...","[Drama, Romance]","[MontgomeryClift, ElizabethTaylor, ShelleyWint...",[GeorgeStevens],"[An, ambitious, young, man, wins, an, heiress'..."
12624,9029,What Happens in Vegas,"[During, a, wild, vacation, in, Las, Vegas,, c...","[Comedy, Romance]","[AshtonKutcher, CameronDiaz, LakeBell]",[TomVaughan],"[During, a, wild, vacation, in, Las, Vegas,, c..."
18725,59974,Genius Within: The Inner Life of Glenn Gould,"[A, documentary, on, the, mysterious, and, inf...","[Documentary, Music]",[GlennGould],"[MichèleHozer, PeterRaymont]","[A, documentary, on, the, mysterious, and, inf..."
33970,323370,The Diabolical,"[When, a, single, mother, and, her, two, young...","[Horror, ScienceFiction, Thriller]","[AliLarter, MerrinDungey, PatrickFischler]",[AlistairLegrand],"[When, a, single, mother, and, her, two, young..."
2179,1091,The Thing,"[Scientists, in, the, Antarctic, are, confront...","[Horror, Mystery, ScienceFiction]","[KurtRussell, KeithDavid, WilfordBrimley]",[JohnCarpenter],"[Scientists, in, the, Antarctic, are, confront..."
35153,218275,The Letters,"[MOTHER, TERESA,, recipient, of, the, Nobel, P...",[Drama],"[RutgerHauer, JulietStevenson, MaxvonSydow]",[WilliamRiead],"[MOTHER, TERESA,, recipient, of, the, Nobel, P..."
39712,29924,Around the World in 80 Days,"[Around, the, World, in, 80, Days, is, a, 1989...","[Adventure, Drama]","[PierceBrosnan, EricIdle, PeterUstinov]",[BuzzKulik],"[Around, the, World, in, 80, Days, is, a, 1989..."
40129,407887,Operation Chromite,"[A, squad, of, soldiers, fight, in, the, Korea...","[History, Drama, War, Action]","[LeeJung-jae, LiamNeeson, LeeBeom-soo]",[JohnH.Lee],"[A, squad, of, soldiers, fight, in, the, Korea..."
29724,3699,Seven Blood-Stained Orchids,"[A, woman,, a, survivor, of, a, failed, murder...","[Mystery, Crime, Horror]","[AntonioSabàto, UschiGlas, MarisaMell]",[UmbertoLenzi],"[A, woman,, a, survivor, of, a, failed, murder..."
26804,19183,The Derby Stallion,"[An, alcoholic, former, horse-trainer, perceiv...","[Drama, Family]","[ZacEfron, BillCobbs, WilliamR.Moses]",[CraigClyde],"[An, alcoholic, former, horse-trainer, perceiv..."
30596,11218,Rhythm is it!,"[RHYTHM, IS, IT!, records, the, first, big, ed...",[Documentary],"[RoystonMaldoom, SusannahBroughton, MarieThein...","[ThomasGrube, EnriqueSánchezLansch]","[RHYTHM, IS, IT!, records, the, first, big, ed..."
9118,26103,Mean Guns,"[One, hundred, mid-, and, low-level, gangsters...","[Action, Adventure, Crime, Thriller]","[ChristopherLambert, Ice-T, MichaelHalsey]",[AlbertPyun],"[One, hundred, mid-, and, low-level, gangsters..."
11629,26655,Like Mike 2: Streetball,"[Another, young, boy, with, 'hoop, dreams', fi...","[Comedy, Drama, Family]","[JaschaWashington, KelMitchell, MichaelBeach]",[DavidNelson],"[Another, young, boy, with, 'hoop, dreams', fi..."
15431,43780,One of Our Aircraft Is Missing,"[During, the, Allied, Bombing, offensive, of, ...","[Action, War, Drama]","[GodfreyTearle, EricPortman, HughWilliams]","[EmericPressburger, MichaelPowell]","[During, the, Allied, Bombing, offensive, of, ..."
11024,350,The Devil Wears Prada,"[The, Devil, Wears, Prada, is, about, a, young...","[Comedy, Drama, Romance]","[MerylStreep, AnneHathaway, EmilyBlunt]",[DavidFrankel],"[The, Devil, Wears, Prada, is, about, a, young..."

In [5]:
movies_1.head(2)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0

In [6]:
movies_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [7]:
credits_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [8]:
# change the datatype of credits_1 'id' feature int-->str
credits_1['id']=credits_1['id'].astype(str)

In [9]:
credits_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  object
dtypes: object(3)
memory usage: 1.0+ MB

In [10]:
movies_1.shape

(45466, 24)

In [11]:
credits_1.shape

(45476, 3)

In [12]:
credits_1.columns

Index(['cast', 'crew', 'id'], dtype='object')

In [13]:
movies_1 = movies_1.merge(credits_1,on='id')

In [14]:
movies_1.head(2)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,cast,crew
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."

In [15]:
# we change the column name  belongs_to_collection to keywords.
movies_1.rename(columns={'belongs_to_collection':'keywords'}, inplace=True)

In [16]:
movies_1.rename(columns={'id':'movie_id'}, inplace = True)

In [17]:
movies_1 = movies_1[['movie_id','title','overview','genres','cast','crew']]

In [18]:
movies_1.head(2)

,movie_id,title,overview,genres,cast,crew
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."

In [19]:
movies_1.isnull().sum()

movie_id      0
title         3
overview    954
genres        0
cast          0
crew          0
dtype: int64

In [20]:
movies_1.dropna(inplace=True)    # removes missing or null values

In [21]:
movies_1.duplicated().sum()  #  duplicates found

np.int64(99)

In [22]:
movies_1 = movies_1.drop_duplicates()   # removes duplicate values

In [23]:
movies_1.duplicated().sum()      # 0 duplicate

np.int64(0)

In [24]:
movies_1.iloc[0].genres

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [25]:
import ast

In [26]:

def convert_1(text):    
    T = []
    for i in ast.literal_eval(text):
        T.append(i['name']) 
    return T
def convert(text):    
    T = []
    for i in ast.literal_eval(text):
        T.append(i['name']) 
    return T

In [27]:
ast.literal_eval("[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]")

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [28]:
movies_1['genres'] = movies_1['genres'].apply(convert_1)   
movies_1.head(2)

,movie_id,title,overview,genres,cast,crew
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."

In [29]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [30]:
movies_1['cast'] = movies_1['cast'].apply(convert)
movies_1.head(2)

,movie_id,title,overview,genres,cast,crew
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."

In [31]:
movies_1['cast'] = movies_1['cast'].apply(lambda x:x[0:3])

In [32]:
def fetch_director_1(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [33]:
movies_1['crew'] = movies_1['crew'].apply(fetch_director_1)

In [34]:
movies_1['overview'] = movies_1['overview'].apply(lambda x:x.split())
movies_1.sample(5)

,movie_id,title,overview,genres,cast,crew
29432,43789,Andy Hardy's Private Secretary,"[Andy's, gone, and, done, it, this, time., All...","[Comedy, Romance]","[Lewis Stone, Mickey Rooney, Fay Holden]",[George B. Seitz]
9379,20164,Bad Boys,"[The, story, bases, on, four, Finnish, brother...","[Action, Drama, Comedy]","[Peter Franzén, Niko Saarela, Lauri Nurkse]",[Aleksi Mäkelä]
22493,53389,Trader Games,"[A, hot, young, Wall, Street, trader, finds, a...","[Drama, Thriller, Foreign]","[Gilles Lellouche, Vahina Giocante, Charles Be...",[Fabrice Genestal]
12775,15125,Dante 01,"[Deep, space,, at, the, edge, of, the, galaxy....",[Science Fiction],"[Lambert Wilson, Linh Đan Phạm, Simona Maicane...",[Marc Caro]
24831,194393,The Disembodied,"[When, men, on, a, photo, safari, stumble, int...",[Horror],"[Paul Burke, Allison Hayes, John Wengraf]",[Walter Grauman]

In [35]:
def collapse_1(L):
    T1 = []
    for i in L:
        T1.append(i.replace(" ",""))
    return T1

In [36]:
movies_1['cast'] = movies_1['cast'].apply(collapse_1)
movies_1['crew'] = movies_1['crew'].apply(collapse_1)
movies_1['genres'] = movies_1['genres'].apply(collapse_1)

In [37]:
movies_1.head(2)

,movie_id,title,overview,genres,cast,crew
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter]
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston]

In [38]:
movies_1['tags'] = movies_1['overview'] + movies_1['genres'] + movies_1['cast'] + movies_1['crew']

In [39]:
new_df1 = movies_1[['movie_id','title','tags']]

In [40]:
new_df1.head(2)

  movie_id      title                                               tags
0      862  Toy Story  [Led, by, Woody,, Andy's, toys, live, happily,...
1     8844    Jumanji  [When, siblings, Judy, and, Peter, discover, a...

In [41]:
print(new_df1['tags'].iloc[0])

['Led', 'by', 'Woody,', "Andy's", 'toys', 'live', 'happily', 'in', 'his', 'room', 'until', "Andy's", 'birthday', 'brings', 'Buzz', 'Lightyear', 'onto', 'the', 'scene.', 'Afraid', 'of', 'losing', 'his', 'place', 'in', "Andy's", 'heart,', 'Woody', 'plots', 'against', 'Buzz.', 'But', 'when', 'circumstances', 'separate', 'Buzz', 'and', 'Woody', 'from', 'their', 'owner,', 'the', 'duo', 'eventually', 'learns', 'to', 'put', 'aside', 'their', 'differences.', 'Animation', 'Comedy', 'Family', 'TomHanks', 'TimAllen', 'DonRickles', 'JohnLasseter']

In [42]:
new_df1['tags'] = new_df1['tags'].apply(lambda x: " ".join(x))

C:\Users\Mitesh Soni\AppData\Local\Temp\ipykernel_16892\1031440688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df1['tags'] = new_df1['tags'].apply(lambda x: " ".join(x))

In [43]:
new_df1['tags'] = new_df1['tags'].apply(lambda x:x.lower())

C:\Users\Mitesh Soni\AppData\Local\Temp\ipykernel_16892\3476310363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df1['tags'] = new_df1['tags'].apply(lambda x:x.lower())

In [44]:
new_df1.count('rows')

movie_id    44482
title       44482
tags        44482
dtype: int64

In [45]:
from nltk.stem.porter import PorterStemmer
ps_1= PorterStemmer()

In [46]:
def stem(text):
    z=[ ]

    for i in text.split() :
        z.append(ps_1.stem(i))
    return " ".join(z)

In [47]:
ps_1.stem('actiones')

'action'

In [48]:
new_df1 = new_df1.drop_duplicates()

In [49]:
new_df1.duplicated().sum()

np.int64(0)

In [50]:
new_df1['movie_id'] = new_df1['movie_id'].astype(int)

In [51]:
new_df1.shape

(44476, 3)

In [52]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [53]:
movies.shape

(4803, 20)

In [54]:
credits.shape

(4803, 4)

In [55]:
movies= movies.merge(credits,on='title')

In [56]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

### we take only these columns from dataset and others are removed :

1. movie_id		
2. overview
3. genres
4. keywords	
5. cast	
6. crew
7. title

In [57]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [58]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [59]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [60]:
movies.dropna(inplace=True)    # it removes missing value from data

In [61]:
movies.duplicated().sum()     # checks there is any duplicate value in data

np.int64(0)

In [62]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [63]:
# this code will convert the genres feature  from this :
# [{"id": 28, "name": "Action"}, {"id": 12, "nam... 'Adventure}, ...etc     # this 
#   to this :
# ['Action', 'Adventure', 'Fantasy', 'ScienceFiction'

def convert(text):    
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L
def convert(text):    
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [64]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [65]:
movies['genres'] = movies['genres'].apply(convert)    # apply convert function on column genres 
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [66]:
movies['keywords'] = movies['keywords'].apply(convert)   # apply convert function on keywords columns 
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [67]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [68]:
# we will take top 3 actors name for each movies :
movies['cast'] = movies['cast'].apply(convert)
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [69]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [70]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [71]:
# we will extract the director names from crew data  for each movie:  
movies['crew'] = movies['crew'].apply(fetch_director)

In [ ]:
# we will convert the string overview column into list :
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
2354,20483,Catch That Kid,"[Athletic, 12-year-old, Maddy, (Kristen, Stewa...","[Family, Action, Adventure]",[bank robbery],"[Kristen Stewart, Corbin Bleu, Max Thieriot]","[Bart Freundlich, James Sbardellati, Peter Mer..."
2368,848,Dragonslayer,"[The, sorcerer, and, his, apprentice, Galen, a...",[Fantasy],"[secret identity, self sacrifice, magic, virgi...","[Peter MacNicol, Caitlin Clarke, Ralph Richard...",[Matthew Robbins]
4310,98369,Blue Like Jazz,"[A, young, man, must, find, his, own, way, as,...","[Drama, Comedy]",[book store],"[Marshall Allman, Claire Holt, Tania Raymonde]",[Steve Taylor]
458,41515,Yogi Bear,"[Jellystone, Park, has, been, losing, business...","[Comedy, Family, Animation, Adventure]","[picnic, sandwich, bear, 3d, yogi]","[Dan Aykroyd, Justin Timberlake, Anna Faris]",[Eric Brevig]
4440,2009,"4 Months, 3 Weeks and 2 Days","[Gabita, is, pregnant,, abortion, is, strictly...",[Drama],"[rape, hotel room, totalitarian regime, cohabi...","[Anamaria Marinca, Laura Vasiliu, Vlad Ivanov]",[Cristian Mungiu]

In [73]:
# we will remove spaces between sentences from the dataset on  columns :(cast,crew,genres,keywords)
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [74]:
# and applying the collapse function to each columns 
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [75]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [76]:
# concatinate the 5 columns to make a new column which name is tags :
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [ ]:
# join the columns 
new_df = movies[['movie_id','title','tags']] 
new_df.head(2)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."

In [78]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head(2)

C:\Users\Mitesh Soni\AppData\Local\Temp\ipykernel_16892\2337206404.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."

In [79]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())
new_df.head(2)

C:\Users\Mitesh Soni\AppData\Local\Temp\ipykernel_16892\3744629507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."

In [80]:
import nltk

In [81]:
# we do steming : loved,loving,love == love 
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [82]:
def stem(text):
    y=[ ]

    for i in text.split() :
        y.append(ps.stem(i))
    return " ".join(y)

In [83]:
ps.stem('loved')

'love'

In [84]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Mitesh Soni\AppData\Local\Temp\ipykernel_16892\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

  ### now we merge the TMDB and IMDB dataset :
1. new_df1     (imdb dataset)
2. new_df      (tmdb dataset)

In [85]:
new_movies_df = pd.concat([new_df, new_df1], ignore_index=True)
new_movies_df = new_movies_df.drop_duplicates(subset='movie_id')

In [86]:
new_movies_df.shape

(44681, 3)

In [87]:
new_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44681 entries, 0 to 49281
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  44681 non-null  int64
 1   title     44681 non-null  object
 2   tags      44681 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB

In [88]:
new_movies_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
49277,439050,Subdue,rising and falling between a man and woman. dr...
49278,111109,Century of Birthing,an artist struggles to finish his work while a...
49279,67758,Betrayal,"when one of her hits goes wrong, a professiona..."
49280,227506,Satan Triumphant,"in a small town live two brothers, one a minis..."
49281,461257,Queerama,50 years after decriminalisation of homosexual...

In [89]:
new_movies_df['title'].duplicated().sum()

np.int64(3119)

In [ ]:
# duplicated title(movies) found 
duplicate_titles = new_movies_df[
    new_movies_df['title'].duplicated(keep=False)
].sort_values('title')

print(duplicate_titles[['movie_id', 'title']].head(20))

       movie_id                         title
29001    118658                    10 Minutes
46636    244046                    10 Minutes
4605        389                  12 Angry Men
19938     12219                  12 Angry Men
37112     31648                     12 Chairs
37098     27934                     12 Chairs
28695      2965  20,000 Leagues Under the Sea
3570        173  20,000 Leagues Under the Sea
25493      2966  20,000 Leagues Under the Sea
17770     30266  20,000 Leagues Under the Sea
25300     25038                          2:22
48796    269795                          2:22
1020       5176                  3:10 to Yuma
9950      14168                  3:10 to Yuma
27146     31334                      47 Ronin
84        64686                      47 Ronin
40875     45677                       7 Years
45727    423093                       7 Years
27592    109404                             8
44570    231762                             8

In [93]:
print("Total rows:", len(new_movies_df))
print("Unique titles:", new_movies_df['title'].nunique())

Total rows: 44681
Unique titles: 41562

In [94]:
new_movies_df = new_movies_df.drop_duplicates(subset='title')

In [95]:
new_movies_df['title'].duplicated().sum()

np.int64(0)

In [96]:
new_movies_df.shape

(41562, 3)

In [97]:
# because of memory issue we use only 10000 rows dataset 
new_movies_df = new_movies_df.head(10000)

In [98]:
new_movies_df = new_movies_df.drop_duplicates(subset='title')
new_movies_df.reset_index(drop=True, inplace=True)

In [120]:
print(new_movies_df['movie_id'].duplicated().sum())

0

In [101]:
print(new_movies_df.shape)

(10000, 3)

In [102]:
print(new_movies_df['title'].nunique())

10000

In [103]:
# remove stopwords(in , is , are , it ...etc) drom tags column 
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

In [104]:
vector = tfidf.fit_transform(new_movies_df['tags']).toarray()

In [105]:
vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(10000, 5000))

In [106]:
vector.shape

(10000, 5000)

In [107]:

from sklearn.metrics.pairwise import cosine_similarity

In [108]:
similarity = cosine_similarity(vector)

In [109]:
similarity

array([[1.        , 0.03155222, 0.03977707, ..., 0.        , 0.        ,
        0.00552303],
       [0.03155222, 1.        , 0.01835221, ..., 0.        , 0.        ,
        0.00605589],
       [0.03977707, 0.01835221, 1.        , ..., 0.        , 0.00762068,
        0.00611645],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.00307393,
        0.02658947],
       [0.        , 0.        , 0.00762068, ..., 0.00307393, 1.        ,
        0.        ],
       [0.00552303, 0.00605589, 0.00611645, ..., 0.02658947, 0.        ,
        1.        ]], shape=(10000, 10000))

In [110]:
new_movies_df[new_movies_df['title'] == 'Jumanji'].index[0]

np.int64(4797)

In [111]:
def recommend(movie):
    movie_index = new_movies_df[new_movies_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list= sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_movies_df.iloc[i[0]].title)

In [112]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
The Avengers
Captain America: Civil War

In [113]:
# simelarity score :
movie_index = new_movies_df[new_movies_df['title'] == 'Iron Man'].index[0]

for idx, score in sorted(
    list(enumerate(similarity[movie_index])),
    key=lambda x: x[1],
    reverse=True
)[:10]:
    print(score, new_movies_df.iloc[idx].title)

1.0000000000000004 Iron Man
0.46908626216188565 Iron Man 2
0.4400272287279434 Iron Man 3
0.3624975576917888 Avengers: Age of Ultron
0.25214478238767457 The Avengers
0.245844370534145 Captain America: Civil War
0.23020755049354225 Ant-Man
0.22414018069292668 Thor: The Dark World
0.204638086747096 Thor
0.20347653228533105 Guardians of the Galaxy

In [114]:
import pickle

In [115]:
pickle.dump(new_movies_df.to_dict(),open('new_movie_dict.pkl','wb'))

In [116]:
new_movies_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
9995,183252,Perfectly normal,a cab driver and an opera fan strike up an unu...
9996,3777,Throne of Blood,mikio and washizu are the commanders of the 1s...
9997,11659,The Best of Youth,"spanning four decades, from the chaotic 1960s ..."
9998,24065,Guncrazy,california teen anita minteer struggles in the...
9999,39907,Bang Rajan,set right before the fall of thailand's old ca...

In [ ]:
pickle.dump(similarity,open('similarity_movie.pkl','wb'))